# Generated by Django 3.2.8 on 2021-11-12 07:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_remove_user_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='_network_user_followers_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
