# Generated by Django 3.2.8 on 2021-11-12 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_user_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
    ]
