# Generated by Django 3.2.8 on 2021-11-12 07:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20211112_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='follows',
            field=models.ManyToManyField(blank=True, null=True, related_name='_network_user_follows_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
