# Generated by Django 3.2.8 on 2021-11-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markethelper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='pricecurrent',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
