# Generated by Django 3.2.8 on 2022-01-11 14:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markethelper', '0003_rename_ticket_share_ticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='rating',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
    ]
