# Generated by Django 3.2.8 on 2022-01-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markethelper', '0004_share_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
