# Generated by Django 3.2.8 on 2022-01-30 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markethelper', '0006_events'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
