# Generated by Django 3.2.8 on 2022-01-30 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markethelper', '0007_rename_events_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_type',
        ),
    ]
