# Generated by Django 3.2.8 on 2022-01-30 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('markethelper', '0009_alter_event_share_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='share_related',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='markethelper.share'),
        ),
    ]
