# Generated by Django 3.2.8 on 2021-10-26 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20211027_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='count',
            field=models.IntegerField(default='0'),
        ),
    ]
