# Generated by Django 3.2.8 on 2021-10-27 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_rename_count_bid_bidcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='isopen',
            field=models.BooleanField(default=True),
        ),
    ]
